### ISSUE TITLE
could not find function "reactivePlot"

### ISSUE THREAD

**Issue by AndyBunn** [rstudio/shiny_example#3]
I just tried to run this via:
```
runGitHub("shiny_example", "rstudio")
```
And get the error
```
Error in reactivePlot(width = 400, height = 300, function() { : 
  could not find function "reactivePlot"
```
Is this because `reactivePlot` has been deprecated?

**Comment by wch** [comment]
Oh wow, this is an ancient repository. Yes, `reactivePlot` has been deprecated. I would suggest not using this repository. How did you come across it?

**Comment by AndyBunn** [comment]
It’s in the example for `runGitHub`

From: Winston Chang ***@***.***>
Date: Friday, June 17, 2022 at 4:14 PM
To: rstudio/shiny_example ***@***.***>
Cc: Andy Bunn ***@***.***>, Author ***@***.***>
Subject: Re: [rstudio/shiny_example] could not find function "reactivePlot" (Issue #3)

Oh wow, this is an ancient repository. Yes, reactivePlot has been deprecated. I would suggest not using this repository. How did you come across it?

**Comment by wch** [comment]
Ah, thanks, the it's probably best if we fix it here.

**Comment by wch** [comment]
I've updated the code, in 03b7685 and 7923c05. Thanks for the report.
